/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Clases.Administrador;
import Clases.Clientes;
import Clases.Recepcionista;
import Clases.Tecnicos;
import Clases.Tickets;
import baseDatos.ConexionBd;
import baseDatos.FuncionesBD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yovany Forero
 */
public class JefeTecnico extends javax.swing.JFrame {

    /**
     * Creates new form JefeTecnico
     */
    public JefeTecnico() {
        initComponents();
        
        try {
            con = Con.conectar();
            PreparedStatement PPT = null;
            PPT = con.prepareStatement("Select identificacion From tecnico");
            ResultSet rs = PPT.executeQuery();
            while (rs.next()) {
                String a = rs.getString("identificacion");
                CbxNombreTec.addItem(a);
                CbxNombreTec.setSelectedIndex(0);
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "error por "+ex);
        }
        try {
            tablaTickets();
        } catch (Exception e) {
        }
        
        
             
    }
    private static final login validar = new login();
    
    private static final ConexionBd Con = new ConexionBd();
    private static final FuncionesBD FunBD = new FuncionesBD();
    private Connection con = null;
    private ArrayList<Administrador> adminis;
    private ArrayList<Clientes> client;
    private ArrayList<Clases.JefeTecnico> JefeTec;
    private ArrayList<Tecnicos> Tecni;
    private ArrayList<Recepcionista> recepcionista;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        DateFchaInstalacion = new com.toedter.calendar.JDateChooser();
        TxtHoraInstalacion = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TxtTipoServi = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        TxtIdentiClien = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        TxtBarriClien = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        TxtNombClie = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        TxtDireciCli = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        TxtTelefoClien = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        CbxNombreTec = new javax.swing.JComboBox();
        jScrollPane4 = new javax.swing.JScrollPane();
        TbTickes = new javax.swing.JTable();
        CbxServicioRea = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TbReportes = new javax.swing.JTable();
        DateFechaInicial = new com.toedter.calendar.JDateChooser();
        DateFechaFinal = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Codigo");
        jLabel6.setToolTipText("");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Fecha Instalacion");
        jLabel11.setToolTipText("");

        try {
            TxtHoraInstalacion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:## ")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TxtHoraInstalacion.setToolTipText("");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Hora Instalacion");
        jLabel12.setToolTipText("");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Tipo Servicio a Realizar");
        jLabel13.setToolTipText("");

        TxtTipoServi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Servicio Realizado");
        jLabel14.setToolTipText("");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Identicacion Tecnico a realizar servicio");
        jLabel15.setToolTipText("");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Identificacion Cliente");
        jLabel16.setToolTipText("");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Barrio Cliente");
        jLabel17.setToolTipText("");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Nombre Cliente");
        jLabel18.setToolTipText("");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Direccion Cliente");
        jLabel19.setToolTipText("");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Telefono Cliente");
        jLabel20.setToolTipText("");

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        CbxNombreTec.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CbxNombreTec.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Seleccionar-" }));

        TbTickes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(TbTickes);

        CbxServicioRea.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Seleccionar-", "Si", "No" }));

        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(DateFchaInstalacion, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel14))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(CbxServicioRea, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(TxtHoraInstalacion, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TxtIdentiClien, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TxtNombClie, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TxtDireciCli, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TxtBarriClien, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(TxtTipoServi))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(CbxNombreTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel20)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(TxtTelefoClien, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 566, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel16)
                                .addComponent(TxtIdentiClien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(DateFchaInstalacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(TxtHoraInstalacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19)
                                    .addComponent(TxtDireciCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(TxtNombClie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(CbxServicioRea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(TxtBarriClien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(CbxNombreTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(TxtTelefoClien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(TxtTipoServi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ingreso Tickets", jPanel3);

        jScrollPane2.setViewportView(TbReportes);

        DateFechaInicial.setDateFormatString("yyyy/MM/d");
        DateFechaInicial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        DateFechaFinal.setDateFormatString("yyyy/MM/d");
        DateFechaFinal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Fecha Inicial");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Fecha Final");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Reporte");

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setText("Volver");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(DateFechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton5))
                                    .addComponent(DateFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(628, 628, 628)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(DateFechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton5))
                        .addGap(2, 2, 2)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DateFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jTabbedPane1.addTab("Reportes", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean validacion(String cadena){
        int num;
        try {
            num = Integer.parseInt(cadena);
            return true;
        } catch (Exception e) {
            return false;
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if (txtCodigo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese el codigo del ticket");
            return;
        }
        boolean v = validacion(txtCodigo.getText());
        if (v != false) {
            
        }else{
            JOptionPane.showMessageDialog(null, "solo se registra numeros");
            return;
        }
        String Codigo = (txtCodigo.getText());
        
        String dia = Integer.toString(DateFchaInstalacion.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mes = Integer.toString(DateFchaInstalacion.getCalendar().get(Calendar.MONTH));
        String ano = Integer.toString(DateFchaInstalacion.getCalendar().get(Calendar.YEAR));
        String fecha = ano+"/"+mes+"/"+dia;
        if (TxtHoraInstalacion.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese el codigo");
            return;
        }
        String HoraInstalacion = TxtHoraInstalacion.getText();
        if (CbxNombreTec.getSelectedItem().equals("-Seleccionar-")) {
            JOptionPane.showMessageDialog(null, "Seleccione la identificacion del tecnico que va a realizar el servicio");
            return;
        }
        String IdentificacionTecnico = CbxNombreTec.getSelectedItem().toString();
        if (TxtTipoServi.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "ingrese el tipo del servicio a realizar");
            return;
        }
        String Observaciones = TxtTipoServi.getText();
        
         if (CbxServicioRea.getSelectedItem().equals("-Seleccionar-")) {
            JOptionPane.showMessageDialog(null, "Seleccione una opcion en Servicio Realizado");
            return;
        }
        String ServicioRealizado = CbxServicioRea.getSelectedItem().toString();
        Tickets tis = new Tickets(Codigo, fecha, HoraInstalacion, IdentificacionTecnico, ServicioRealizado, Observaciones);
        
        if (TxtIdentiClien.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Ingrese la identificacion del cliente");
                return;
            }
            boolean a = validacion(TxtIdentiClien.getText());
            if (a != false) {
            
            }else{
                JOptionPane.showMessageDialog(null, "solo se registra numeros");
                return;
            }

        if (TxtNombClie.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Ingrese el nombre del cliente");
                return;
            }
        if (TxtDireciCli.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Ingrese la direccion del cliente");
                return;
            }
        if (TxtBarriClien.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Ingrese el nombre del barrio del cliente");
                return;
            }
        if (TxtTelefoClien.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Ingrese el telefono del cliente");
                return;
            }
        FunBD.InsercionTickets(tis);
        try {
            
            String sql = "SELECT COUNT(id) from tickets";
            con = Con.conectar();
            PreparedStatement ppt = con.prepareStatement(sql);
            ResultSet rs = ppt.executeQuery();
            rs.beforeFirst();
            rs.next();
            Integer id = rs.getInt("COUNT(id)");  
            
            
            String identicacionClien = TxtIdentiClien.getText();
            
            String nombre = TxtNombClie.getText();
            
            String direccion = TxtDireciCli.getText();
            
            String barrio = TxtBarriClien.getText();
            
            String Telefono = TxtTelefoClien.getText();
            Clientes cli = new Clientes(identicacionClien, nombre, direccion, barrio, Telefono, id);
            
            FunBD.InsercionCliente(cli);

            limpiarjacaTickes();
            tablaTickets();
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tablaTickets() throws SQLException {
        DefaultTableModel Modelo6 = new DefaultTableModel();
        Modelo6.addColumn("Codigo");
        Modelo6.addColumn("Fecha Instalacion");
        Modelo6.addColumn("Horario de visita");
        Modelo6.addColumn("Tipo Servicio");
        Modelo6.addColumn("Servicio Realizado");
        Modelo6.addColumn("Identificacion usuario");
        Modelo6.addColumn("Nombre Del Usuario");
        Modelo6.addColumn("Telefono del usuario");
        Modelo6.addColumn("Direccion Usuario");
        Modelo6.addColumn("Barrio");
        this.TbTickes.setModel(Modelo6);
        String sql = "select e.codigo, "
                + "e.fechaInstalacion, "
                + "e.horario, "
                + "e.TipoServicio,"
                + " e.servicioRealizado,"
                + " u.identificacionCliente, "
                + "u.NombreCliente,"
                + " u.Telefono,"
                + " u.Direccion,"
                + " u.nombreBarrio "
                + "FROM tickets e "
                + "INNER JOIN usuarios u"
                + " ON e.id = u.idTicket ";
               
        con = Con.conectar();
        String fila[] = new String[10];
        try {               
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {                
                fila[0] = rs.getString(1);
                fila[1] = rs.getString(2);
                fila[2] = rs.getString(3);
                fila[3] = rs.getString(4);
                fila[4] = rs.getString(5);
                fila[5] = rs.getString(6);
                fila[6] = rs.getString(7);
                fila[7] = rs.getString(8);
                fila[8] = rs.getString(9);
                fila[9] = rs.getString(10);
                Modelo6.addRow(fila);
                this.TbTickes.setModel(Modelo6);
            }                         
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error: jon " + e);
        }
    }
    
    private void limpiarjacaTickes() {
        txtCodigo.setText("");
        TxtHoraInstalacion.setText("");
        CbxNombreTec.setSelectedIndex(0);
        TxtTipoServi.setText("");
        CbxServicioRea.setSelectedIndex(0);
        TxtIdentiClien.setText("");
        TxtNombClie.setText("");
        TxtDireciCli.setText("");
        TxtTelefoClien.setText("");
        TxtBarriClien.setText("");
    }
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultTableModel Modelo6 = new DefaultTableModel();
        Modelo6.addColumn("Codigo");
        Modelo6.addColumn("Fecha Instalacion");
        Modelo6.addColumn("Horario de visita");
        Modelo6.addColumn("Tipo Servicio");
        Modelo6.addColumn("Servicio Realizado");
        Modelo6.addColumn("Nombre Tecnico");
        Modelo6.addColumn("Nombre Del Usuario");
        this.TbReportes.setModel(Modelo6);
        String dia1 = Integer.toString(DateFechaInicial.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mes1 = Integer.toString(DateFechaInicial.getCalendar().get(Calendar.MONTH));
        String ano1 = Integer.toString(DateFechaInicial.getCalendar().get(Calendar.YEAR));
        String dia2 = Integer.toString(DateFechaFinal.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mes2 = Integer.toString(DateFechaFinal.getCalendar().get(Calendar.MONTH));
        String ano2 = Integer.toString(DateFechaFinal.getCalendar().get(Calendar.YEAR));
        String  date1 = ano1+"-"+mes1+"-"+dia1;
        String  date2 = ano2+"-"+mes2+"-"+dia2;

        try {

            String sql = "select "
                    + "e.codigo, "
                    + "e.fechaInstalacion,"
                    + "e.horario,"
                    + "e.TipoServicio,"
                    + "e.servicioRealizado,"
                    + "t.nombre,"
                    + "u.NombreCliente "
                    + "FROM tickets e "
                    + "INNER JOIN usuarios u ON e.id = u.idTicket "
                    + "INNER JOIN tecnico t on t.identificacion = e.identificacionEmpleado "
                    + "WHERE e.fechaInstalacion BETWEEN '"+date1+"' AND '"+date2+"' "
                    + "ORDER BY e.fechaInstalacion, e.horario ";
            con = Con.conectar();

            PreparedStatement ppt = con.prepareStatement(sql);
            String fila[] = new String[7];
            ResultSet rs = ppt.executeQuery();
            while (rs.next()) {
                fila[0] = rs.getString(1);
                fila[1] = rs.getString(2);
                fila[2] = rs.getString(3);
                fila[3] = rs.getString(4);
                fila[4] = rs.getString(5);
                fila[5] = rs.getString(6);
                fila[6] = rs.getString(7);
                Modelo6.addRow(fila);
                this.TbReportes.setModel(Modelo6);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      login log = new login();
        log.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        login log = new login();
        log.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JefeTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JefeTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JefeTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JefeTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JefeTecnico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CbxNombreTec;
    private javax.swing.JComboBox CbxServicioRea;
    private com.toedter.calendar.JDateChooser DateFchaInstalacion;
    private com.toedter.calendar.JDateChooser DateFechaFinal;
    private com.toedter.calendar.JDateChooser DateFechaInicial;
    private javax.swing.JTable TbReportes;
    private javax.swing.JTable TbTickes;
    private javax.swing.JTextField TxtBarriClien;
    private javax.swing.JTextField TxtDireciCli;
    private javax.swing.JFormattedTextField TxtHoraInstalacion;
    private javax.swing.JTextField TxtIdentiClien;
    private javax.swing.JTextField TxtNombClie;
    private javax.swing.JTextField TxtTelefoClien;
    private javax.swing.JTextField TxtTipoServi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
}
