/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import baseDatos.ConexionBd;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Yovany Forero
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }
    public boolean valadmin = false;
    public boolean valjefe = false;
    public boolean valrecep = false;
    public boolean valtecni = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Btnlogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtPasword = new javax.swing.JPasswordField();
        CbxNomUsuario = new javax.swing.JComboBox();
        CbxRol = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        jLabel1.setText("Login");

        jLabel2.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel2.setText("Nombre Usuario");

        jLabel3.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel3.setText("Contraseña");
        jLabel3.setToolTipText("");

        Btnlogin.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Btnlogin.setText("entrar");
        Btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnloginActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel4.setText("Tipo Usuario");

        txtPasword.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPasword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPaswordKeyTyped(evt);
            }
        });

        CbxNomUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        CbxRol.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        CbxRol.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Selecionar-", "Administrador", "Jefe Tecnico", "Recepcionista", "Tecnico" }));
        CbxRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxRolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Btnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPasword)
                                    .addComponent(CbxNomUsuario, 0, 325, Short.MAX_VALUE)
                                    .addComponent(CbxRol, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel1)))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CbxRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CbxNomUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPasword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btnlogin)
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnloginActionPerformed
        String usuario = CbxNomUsuario.getSelectedItem().toString();
        String pass = txtPasword.getText();
        
        Connection Con = null;
        PreparedStatement ppt = null;
        ConexionBd con = new ConexionBd();
        try {
            Con = con.conectar();
            if (CbxRol.getSelectedItem().equals("Administrador")) {
                ppt = Con.prepareStatement("SELECT * FROM administrador WHERE nombre = ? AND contrasena = ?");
                ppt.setString(1, usuario);
                ppt.setString(2, pass);
                ResultSet rs = ppt.executeQuery();
                valadmin = false;
                while (rs.next()) {                    
                    Principal Vp = new Principal();
                    Vp.setVisible(true);
                    setVisible(false);
                    valadmin = true;
                    break;
                }
                if (valadmin == false) {
                    JOptionPane.showMessageDialog(null, "Contraseña incorrecta");
                    txtPasword.setText("");
                }
                //-Selecionar-, Administrador, Jefe Tecnico, 
            }if (CbxRol.getSelectedItem().equals("Jefe Tecnico")) {
                ppt = Con.prepareStatement("SELECT * FROM jefetecnico WHERE nombre = ? AND contrasena = ?");
                ppt.setString(1, usuario);
                ppt.setString(2, pass);
                ResultSet rs = ppt.executeQuery();
                valjefe = false;
                while (rs.next()) {                    
                    JefeTecnico Vp = new JefeTecnico();
                    Vp.setVisible(true);
                    setVisible(false);
                    valjefe = true;
                    break;
                }
                if (valjefe == false) {
                    JOptionPane.showMessageDialog(null, "Contraseña incorrecta");
                    txtPasword.setText("");
                }
            }if (CbxRol.getSelectedItem().equals("Recepcionista")) {
                ppt = Con.prepareStatement("SELECT * FROM recepcionista WHERE nombre = ? AND contrasena = ?");
                ppt.setString(1, usuario);
                ppt.setString(2, pass);
                ResultSet rs = ppt.executeQuery();
                valrecep = false;
                while (rs.next()) {                    
                    recepcionista Vp = new recepcionista();
                    Vp.setVisible(true);
                    setVisible(false);
                    valrecep = true;
                    break;
                }
                if (valrecep == false) {
                    JOptionPane.showMessageDialog(null, "Contraseña incorrecta");
                    txtPasword.setText("");
                }
            }if (CbxRol.getSelectedItem().equals("Tecnico")) {
                ppt = Con.prepareStatement("SELECT * FROM tecnico WHERE nombre = ? AND contrasena = ?");
                ppt.setString(1, usuario);
                ppt.setString(2, pass);
                ResultSet rs = ppt.executeQuery();
                valtecni = false;
                while (rs.next()) {                    
                    tecnico Vp = new tecnico();
                    Vp.setVisible(true);
                    setVisible(false);
                    valtecni = true;
                    break;
                }
                if (valtecni == false) {
                    JOptionPane.showMessageDialog(null, "Contraseña incorrecta");
                    txtPasword.setText("");
                }
            }
            
        } catch (Exception e) {         
            JOptionPane.showMessageDialog(null, "error por: "+ e);

        }       
    }//GEN-LAST:event_BtnloginActionPerformed

    private void CbxRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxRolActionPerformed
        Connection Con = null;
        PreparedStatement ppt = null;
        ConexionBd con = new ConexionBd();
        try {
            Con = con.conectar();
            if (CbxRol.getSelectedItem().equals("Administrador")) {
                
                CbxNomUsuario.removeAllItems();
                ppt = Con.prepareStatement("SELECT nombre FROM administrador");
                ResultSet rs = ppt.executeQuery();
                while (rs.next()) {
                    String a = rs.getString("nombre");
                    CbxNomUsuario.addItem(a);
                    CbxNomUsuario.setSelectedIndex(-1);
                }               
            }
            if (CbxRol.getSelectedItem().equals("Jefe Tecnico")) {
                
                CbxNomUsuario.removeAllItems();
                ppt = Con.prepareStatement("SELECT nombre FROM jefetecnico");
                ResultSet rs = ppt.executeQuery();
                while (rs.next()) {
                    String a = rs.getString("nombre");
                    CbxNomUsuario.addItem(a);
                    CbxNomUsuario.setSelectedIndex(-1);
                }               
            }
            if (CbxRol.getSelectedItem().equals("Recepcionista")) {
                
                CbxNomUsuario.removeAllItems();
                ppt = Con.prepareStatement("SELECT nombre FROM recepcionista");
                ResultSet rs = ppt.executeQuery();
                while (rs.next()) {
                    String a = rs.getString("nombre");
                    CbxNomUsuario.addItem(a);
                    CbxNomUsuario.setSelectedIndex(-1);
                }               
            }
            if (CbxRol.getSelectedItem().equals("Tecnico")) {
                
                CbxNomUsuario.removeAllItems();
                ppt = Con.prepareStatement("SELECT nombre FROM tecnico");
                ResultSet rs = ppt.executeQuery();
                while (rs.next()) {
                    String a = rs.getString("nombre");
                    CbxNomUsuario.addItem(a);
                    CbxNomUsuario.setSelectedIndex(-1);
                }               
            }
            
            //-Selecionar-, Administrador, Jefe Tecnico, Recepcionista, Tecnico
        } catch (Exception e) {
        }
    }//GEN-LAST:event_CbxRolActionPerformed

    private void txtPaswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaswordKeyTyped
        if ((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47
                ||(int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
                ||(int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96
                ||(int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=255){
            JOptionPane.showMessageDialog(null, "no se permite los caracteres $,%,&,/,*,/,-,ñ");
            txtPasword.setText("");
        }
    }//GEN-LAST:event_txtPaswordKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        baseDatos.ConexionBd con = new baseDatos.ConexionBd();
               Connection cons= con.conectar();
               
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnlogin;
    private javax.swing.JComboBox CbxNomUsuario;
    private javax.swing.JComboBox CbxRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txtPasword;
    // End of variables declaration//GEN-END:variables
}
