/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Clases.Administrador;
import Clases.Clientes;
import Clases.JefeTecnico;
import Clases.Recepcionista;
import Clases.Tecnicos;
import Clases.Tickets;
import baseDatos.ConexionBd;
import baseDatos.FuncionesBD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yovany Forero
 */
public class recepcionista extends javax.swing.JFrame {

    /**
     * Creates new form recepcionista
     */
    public recepcionista() {
        initComponents();
        try {
            ConsultarJefe();
        } catch (Exception e) {
        }
        try {
            ConsultarTecnico();
        } catch (Exception e) {
        }
        
             
    }
private static final login validar = new login();
    
    private static final ConexionBd Con = new ConexionBd();
    private static final FuncionesBD FunBD = new FuncionesBD();
    private Connection con = null;
    private ArrayList<Administrador> adminis;
    private ArrayList<Clientes> client;
    private ArrayList<JefeTecnico> JefeTec;
    private ArrayList<Tecnicos> Tecni;
    private ArrayList<Recepcionista> recepcionista;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelActualizarJefe = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        txtIdentificacion2 = new javax.swing.JTextField();
        TxtNombres1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        Txtapellidos1 = new javax.swing.JTextField();
        TxtTelefono1 = new javax.swing.JTextField();
        TxtApellidos1 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        TxtNombreBar1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        TxtCorreo1 = new javax.swing.JTextField();
        DateEmpleados1 = new com.toedter.calendar.JDateChooser();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        TxtPassword1 = new javax.swing.JPasswordField();
        BtnSeleccionar1 = new javax.swing.JButton();
        BtnActualizar1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        TbActualizarJefe = new javax.swing.JTable();
        BtnSeleccionar4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TbReportes = new javax.swing.JTable();
        DateFechaInicial = new com.toedter.calendar.JDateChooser();
        DateFechaFinal = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        BtnSeleccionar5 = new javax.swing.JButton();
        BtnSeleccionar6 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TbActualizarTecnico = new javax.swing.JTable();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        TxtApellidos2 = new javax.swing.JLabel();
        TxtTelefono2 = new javax.swing.JTextField();
        Txtapellidos2 = new javax.swing.JTextField();
        TxtNombres2 = new javax.swing.JTextField();
        txtIdentificacion3 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        TxtPassword2 = new javax.swing.JPasswordField();
        DateEmpleados2 = new com.toedter.calendar.JDateChooser();
        TxtCorreo2 = new javax.swing.JTextField();
        TxtNombreBar2 = new javax.swing.JTextField();
        BtnSeleccionar2 = new javax.swing.JButton();
        BtnActualizar2 = new javax.swing.JButton();
        BtnSeleccionar7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Identificacion");

        txtIdentificacion2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        TxtNombres1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Nombres");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Apellidos");

        Txtapellidos1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        TxtTelefono1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        TxtApellidos1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxtApellidos1.setText("telefono");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Nombre Barrio");

        TxtNombreBar1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Correo");

        TxtCorreo1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("Fecha Nacimiento");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Contraseña");

        TxtPassword1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        BtnSeleccionar1.setText("Seleccionar");
        BtnSeleccionar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSeleccionar1ActionPerformed(evt);
            }
        });

        BtnActualizar1.setText("Actualizar");
        BtnActualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnActualizar1ActionPerformed(evt);
            }
        });

        TbActualizarJefe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(TbActualizarJefe);

        BtnSeleccionar4.setText("Volver");
        BtnSeleccionar4.setToolTipText("");
        BtnSeleccionar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSeleccionar4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelActualizarJefeLayout = new javax.swing.GroupLayout(PanelActualizarJefe);
        PanelActualizarJefe.setLayout(PanelActualizarJefeLayout);
        PanelActualizarJefeLayout.setHorizontalGroup(
            PanelActualizarJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelActualizarJefeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelActualizarJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelActualizarJefeLayout.createSequentialGroup()
                        .addGroup(PanelActualizarJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(TxtApellidos1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelActualizarJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Txtapellidos1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdentificacion2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtNombres1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelActualizarJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelActualizarJefeLayout.createSequentialGroup()
                                .addGroup(PanelActualizarJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel27))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelActualizarJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtPassword1)
                                    .addComponent(DateEmpleados1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(BtnSeleccionar4))
                            .addGroup(PanelActualizarJefeLayout.createSequentialGroup()
                                .addGroup(PanelActualizarJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25))
                                .addGap(23, 23, 23)
                                .addGroup(PanelActualizarJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtNombreBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                                    .addComponent(TxtCorreo1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelActualizarJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BtnSeleccionar1)
                                    .addComponent(BtnActualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelActualizarJefeLayout.setVerticalGroup(
            PanelActualizarJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelActualizarJefeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelActualizarJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelActualizarJefeLayout.createSequentialGroup()
                        .addGroup(PanelActualizarJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(TxtNombreBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnSeleccionar1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelActualizarJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtCorreo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnActualizar1))
                        .addGap(10, 10, 10)
                        .addGroup(PanelActualizarJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DateEmpleados1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnSeleccionar4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelActualizarJefeLayout.createSequentialGroup()
                        .addGroup(PanelActualizarJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(txtIdentificacion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelActualizarJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelActualizarJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TxtNombres1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel25))
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelActualizarJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(Txtapellidos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelActualizarJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtApellidos1)
                            .addComponent(TxtTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Actualizar Jefe Tecnico", PanelActualizarJefe);

        jScrollPane2.setViewportView(TbReportes);

        DateFechaInicial.setDateFormatString("yyyy/MM/d");
        DateFechaInicial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        DateFechaFinal.setDateFormatString("yyyy/MM/d");
        DateFechaFinal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Fecha Inicial");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Fecha Final");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Reporte");

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        BtnSeleccionar5.setText("Volver");
        BtnSeleccionar5.setToolTipText("");
        BtnSeleccionar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSeleccionar5ActionPerformed(evt);
            }
        });

        BtnSeleccionar6.setText("Volver");
        BtnSeleccionar6.setToolTipText("");
        BtnSeleccionar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSeleccionar6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(DateFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(271, 271, 271)
                                .addComponent(jLabel8))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(DateFechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4)
                                .addGap(18, 18, 18)
                                .addComponent(BtnSeleccionar6)))))
                .addGap(538, 538, 538))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(641, 641, 641)
                    .addComponent(BtnSeleccionar5)
                    .addContainerGap(1146, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(DateFechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(BtnSeleccionar6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addComponent(jButton4)
                            .addGap(2, 2, 2))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DateFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(204, 204, 204)
                    .addComponent(BtnSeleccionar5)
                    .addContainerGap(204, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Reportes", jPanel4);

        TbActualizarTecnico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane6.setViewportView(TbActualizarTecnico);

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("Identificacion");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setText("Nombres");

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setText("Apellidos");

        TxtApellidos2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxtApellidos2.setText("telefono");

        TxtTelefono2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        Txtapellidos2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        TxtNombres2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtIdentificacion3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setText("Nombre Barrio");

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setText("Correo");

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel33.setText("Fecha Nacimiento");

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel34.setText("Contraseña");

        TxtPassword2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        TxtCorreo2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        TxtNombreBar2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        BtnSeleccionar2.setText("Seleccionar");
        BtnSeleccionar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSeleccionar2ActionPerformed(evt);
            }
        });

        BtnActualizar2.setText("Actualizar");
        BtnActualizar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnActualizar2ActionPerformed(evt);
            }
        });

        BtnSeleccionar7.setText("Volver");
        BtnSeleccionar7.setToolTipText("");
        BtnSeleccionar7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSeleccionar7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 1321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30)
                            .addComponent(TxtApellidos2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Txtapellidos2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdentificacion3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtNombres2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel32))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtCorreo2, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                                    .addComponent(TxtNombreBar2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnSeleccionar7))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel33)
                                    .addComponent(jLabel34))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(DateEmpleados2, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                                    .addComponent(TxtPassword2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BtnActualizar2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnSeleccionar2))))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(TxtNombreBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtCorreo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnSeleccionar7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DateEmpleados2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnSeleccionar2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnActualizar2)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(txtIdentificacion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TxtNombres2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel32))
                            .addComponent(jLabel29))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(Txtapellidos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtApellidos2)
                            .addComponent(TxtTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Actualizar Tecnico", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1351, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void SeleccionarJefe() throws ParseException {
        int fila = TbActualizarJefe.getSelectedRow();
        if (fila >= 0) {
            txtIdentificacion2.setEnabled(false);
            txtIdentificacion2.setText(TbActualizarJefe.getValueAt(fila, 0).toString());
            TxtNombres1.setText(TbActualizarJefe.getValueAt(fila, 1).toString());
            Txtapellidos1.setText(TbActualizarJefe.getValueAt(fila, 2).toString());
            TxtTelefono1.setText(TbActualizarJefe.getValueAt(fila, 3).toString());
            TxtNombreBar1.setText(TbActualizarJefe.getValueAt(fila, 5).toString());
            TxtCorreo1.setText(TbActualizarJefe.getValueAt(fila,6).toString());
            String[] fecha;
            fecha = TbActualizarJefe.getValueAt(fila, 7).toString().split("-");
            String ano = fecha[0];
            String mes = fecha[1];
            String dia = fecha[2];
            String fes = dia+"/"+mes+"/"+ano;
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            java.util.Date parse = formato.parse(fes);
            DateEmpleados1.setDate(parse);
            TxtPassword1.setText(TbActualizarJefe.getValueAt(fila, 8).toString());
        } else {
            JOptionPane.showMessageDialog(null, "Selecione una fila" );
        }
    }
    private void BtnSeleccionar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSeleccionar1ActionPerformed
        try {
            txtIdentificacion2.setEnabled(false);
            SeleccionarJefe();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"No se pudo realizar la selecion:");

        }
    }//GEN-LAST:event_BtnSeleccionar1ActionPerformed
private void ConsultarJefe() throws SQLException {
       DefaultTableModel modelo2 = new DefaultTableModel();
        modelo2.addColumn("Identificacion");
        modelo2.addColumn("Nombre");
        modelo2.addColumn("Apellido");
        modelo2.addColumn("Telefono");
        modelo2.addColumn("Direccion");
        modelo2.addColumn("Barrio");
        modelo2.addColumn("Correo");
        modelo2.addColumn("Fecha Nacimiento");
        modelo2.addColumn("Contraseña");
        this.TbActualizarJefe.setModel(modelo2);
            //if (CbxConsulIdentificacion.getSelectedItem().equals("Recepsionista")) {
                JefeTec = FunBD.ConsultarJefe();
                while (modelo2.getRowCount()>0) {
                    modelo2.removeRow(0);                
                }
                int numCol= modelo2.getColumnCount();
            
                for (JefeTecnico Recep : JefeTec) {
                    Object[] fila = new Object[numCol];
                    fila[0] = Recep.getIdentificacion();
                    fila[1] = Recep.getNombre();
                    fila[2] = Recep.getApellido();
                    fila[3] = Recep.getTelefono();
                    fila[4] = Recep.getDireccion();
                    fila[5] = Recep.getBarrio();
                    fila[6] = Recep.getCorreo();
                    fila[7] = Recep.getFechaNacimiento();
                    fila[8] = Recep.getContrasena();
                    modelo2.addRow(fila);
                    this.TbActualizarJefe.setModel(modelo2);
                }
    }
    private void BtnActualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActualizar1ActionPerformed
        int fila = TbActualizarJefe.getSelectedRow();

        try {
            String dia = Integer.toString(DateEmpleados1.getCalendar().get(Calendar.DAY_OF_MONTH));
            String Mes = Integer.toString(DateEmpleados1.getCalendar().get(Calendar.MONTH));
            String Ano = Integer.toString(DateEmpleados1.getCalendar().get(Calendar.YEAR));
            String Fecha = (Ano+"-"+Mes+"-"+dia);
            String Identificacon = txtIdentificacion2.getText();
            String Nombre = TxtNombres1.getText();
            String Apellidos = Txtapellidos1.getText();
            String correo = TxtCorreo1.getText();
            String Direccion = TbActualizarJefe.getValueAt(fila, 4).toString();
            String NombreBarrio = TxtNombreBar1.getText();
            String password = TxtPassword1.getText();
            String telefono = TxtTelefono1.getText();
            JefeTecnico empl = new JefeTecnico(password, Identificacon, Nombre, Apellidos, telefono, NombreBarrio, Direccion, Fecha, correo);
            FunBD.ActualizarJefeTec(empl);
            ConsultarJefe();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"error u"+ e);
        }finally{
            limpiarCaja();
            txtIdentificacion2.setEnabled(true);
        }
    }//GEN-LAST:event_BtnActualizar1ActionPerformed
private void limpiarCaja() {
        txtIdentificacion2.setText("");
        TxtNombres1.setText("");
        TxtPassword1.setText("");
        Txtapellidos1.setText("");
        TxtNombreBar1.setText("");
        TxtTelefono1.setText("");
        TxtCorreo1.setText("");
        
    }
    
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultTableModel Modelo6 = new DefaultTableModel();
        Modelo6.addColumn("Codigo");
        Modelo6.addColumn("Fecha Instalacion");
        Modelo6.addColumn("Horario de visita");
        Modelo6.addColumn("Tipo Servicio");
        Modelo6.addColumn("Servicio Realizado");
        Modelo6.addColumn("Nombre Tecnico");
        Modelo6.addColumn("Nombre Del Usuario");
        this.TbReportes.setModel(Modelo6);
        String dia1 = Integer.toString(DateFechaInicial.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mes1 = Integer.toString(DateFechaInicial.getCalendar().get(Calendar.MONTH));
        String ano1 = Integer.toString(DateFechaInicial.getCalendar().get(Calendar.YEAR));
        String dia2 = Integer.toString(DateFechaFinal.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mes2 = Integer.toString(DateFechaFinal.getCalendar().get(Calendar.MONTH));
        String ano2 = Integer.toString(DateFechaFinal.getCalendar().get(Calendar.YEAR));
        String  date1 = ano1+"-"+mes1+"-"+dia1;
        String  date2 = ano2+"-"+mes2+"-"+dia2;

        try {

            String sql = "select "
                    + "e.codigo, "
                    + "e.fechaInstalacion,"
                    + "e.horario,"
                    + "e.TipoServicio,"
                    + "e.servicioRealizado,"
                    + "t.nombre,"
                    + "u.NombreCliente "
                    + "FROM tickets e "
                    + "INNER JOIN usuarios u ON e.id = u.idTicket "
                    + "INNER JOIN tecnico t on t.identificacion = e.identificacionEmpleado "
                    + "WHERE e.fechaInstalacion BETWEEN '"+date1+"' AND '"+date2+"' "
                    + "ORDER BY e.fechaInstalacion, e.horario ";
            con = Con.conectar();

            PreparedStatement ppt = con.prepareStatement(sql);
            String fila[] = new String[7];
            ResultSet rs = ppt.executeQuery();
            while (rs.next()) {
                fila[0] = rs.getString(1);
                fila[1] = rs.getString(2);
                fila[2] = rs.getString(3);
                fila[3] = rs.getString(4);
                fila[4] = rs.getString(5);
                fila[5] = rs.getString(6);
                fila[6] = rs.getString(7);
                Modelo6.addRow(fila);
                this.TbReportes.setModel(Modelo6);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }


    }//GEN-LAST:event_jButton4ActionPerformed

    private void BtnSeleccionar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSeleccionar4ActionPerformed
        login log = new login();
        log.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BtnSeleccionar4ActionPerformed

    private void BtnSeleccionar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSeleccionar5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSeleccionar5ActionPerformed

    private void BtnSeleccionar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSeleccionar6ActionPerformed
         login log = new login();
        log.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BtnSeleccionar6ActionPerformed

    private void BtnSeleccionar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSeleccionar2ActionPerformed
        try {
            txtIdentificacion2.setEnabled(false);
            SeleccionarTecni();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"No se pudo realizar la selecion:");

        }
    }//GEN-LAST:event_BtnSeleccionar2ActionPerformed

    private void ConsultarTecnico() throws SQLException {
        DefaultTableModel modelo2 = new DefaultTableModel();
        modelo2.addColumn("Identificacion");
        modelo2.addColumn("Nombre");
        modelo2.addColumn("Apellido");
        modelo2.addColumn("Telefono");
        modelo2.addColumn("Direccion");
        modelo2.addColumn("Barrio");
        modelo2.addColumn("Correo");
        modelo2.addColumn("Fecha Nacimiento");
        modelo2.addColumn("Contraseña");
        this.TbActualizarTecnico.setModel(modelo2);
            //if (CbxConsulIdentificacion.getSelectedItem().equals("Recepsionista")) {
                Tecni = FunBD.ConsultarTecnicos();
                while (modelo2.getRowCount()>0) {
                    modelo2.removeRow(0);                
                }
                int numCol= modelo2.getColumnCount();
            
                for (Tecnicos Recep : Tecni) {
                    Object[] fila = new Object[numCol];
                    fila[0] = Recep.getIdentificacion();
                    fila[1] = Recep.getNombre();
                    fila[2] = Recep.getApellido();
                    fila[3] = Recep.getTelefono();
                    fila[4] = Recep.getDireccion();
                    fila[5] = Recep.getBarrio();
                    fila[6] = Recep.getCorreo();
                    fila[7] = Recep.getFechaNacimiento();
                    fila[8] = Recep.getContrasena();
                    modelo2.addRow(fila);
                    this.TbActualizarTecnico.setModel(modelo2);
                }
    }
    private void BtnActualizar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActualizar2ActionPerformed
        int fila = TbActualizarTecnico.getSelectedRow();

        try {
            String dia = Integer.toString(DateEmpleados2.getCalendar().get(Calendar.DAY_OF_MONTH));
            String Mes = Integer.toString(DateEmpleados2.getCalendar().get(Calendar.MONTH));
            String Ano = Integer.toString(DateEmpleados2.getCalendar().get(Calendar.YEAR));
            String Fecha = (Ano+"-"+Mes+"-"+dia);
            String Identificacon = txtIdentificacion3.getText();
            String Nombre = TxtNombres2.getText();
            String Apellidos = Txtapellidos2.getText();
            String correo = TxtCorreo2.getText();
            String Direccion = TbActualizarTecnico.getValueAt(fila, 4).toString();
            String NombreBarrio = TxtNombreBar2.getText();
            String password = TxtPassword2.getText();
            String telefono = TxtTelefono2.getText();
            Tecnicos empl = new Tecnicos(password, Identificacon, Nombre, Apellidos, telefono, NombreBarrio, Direccion, Fecha, correo);
            FunBD.Actualizartecnico(empl);
            ConsultarTecnico();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"error u"+ e);
        }finally{
            limpiarCajaTecnico();
            txtIdentificacion2.setEnabled(true);
        }
    }//GEN-LAST:event_BtnActualizar2ActionPerformed

    private void BtnSeleccionar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSeleccionar7ActionPerformed
        login log = new login();
        log.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BtnSeleccionar7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(recepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(recepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(recepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(recepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new recepcionista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActualizar1;
    private javax.swing.JButton BtnActualizar2;
    private javax.swing.JButton BtnSeleccionar1;
    private javax.swing.JButton BtnSeleccionar2;
    private javax.swing.JButton BtnSeleccionar4;
    private javax.swing.JButton BtnSeleccionar5;
    private javax.swing.JButton BtnSeleccionar6;
    private javax.swing.JButton BtnSeleccionar7;
    private com.toedter.calendar.JDateChooser DateEmpleados1;
    private com.toedter.calendar.JDateChooser DateEmpleados2;
    private com.toedter.calendar.JDateChooser DateFechaFinal;
    private com.toedter.calendar.JDateChooser DateFechaInicial;
    private javax.swing.JPanel PanelActualizarJefe;
    private javax.swing.JTable TbActualizarJefe;
    private javax.swing.JTable TbActualizarTecnico;
    private javax.swing.JTable TbReportes;
    private javax.swing.JLabel TxtApellidos1;
    private javax.swing.JLabel TxtApellidos2;
    private javax.swing.JTextField TxtCorreo1;
    private javax.swing.JTextField TxtCorreo2;
    private javax.swing.JTextField TxtNombreBar1;
    private javax.swing.JTextField TxtNombreBar2;
    private javax.swing.JTextField TxtNombres1;
    private javax.swing.JTextField TxtNombres2;
    private javax.swing.JPasswordField TxtPassword1;
    private javax.swing.JPasswordField TxtPassword2;
    private javax.swing.JTextField TxtTelefono1;
    private javax.swing.JTextField TxtTelefono2;
    private javax.swing.JTextField Txtapellidos1;
    private javax.swing.JTextField Txtapellidos2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtIdentificacion2;
    private javax.swing.JTextField txtIdentificacion3;
    // End of variables declaration//GEN-END:variables

    private void SeleccionarTecni() throws ParseException {
        int fila = TbActualizarTecnico.getSelectedRow();
        if (fila >= 0) {
            txtIdentificacion3.setEnabled(false);
            txtIdentificacion3.setText(TbActualizarTecnico.getValueAt(fila, 0).toString());
            TxtNombres2.setText(TbActualizarTecnico.getValueAt(fila, 1).toString());
            Txtapellidos2.setText(TbActualizarTecnico.getValueAt(fila, 2).toString());
            TxtTelefono2.setText(TbActualizarTecnico.getValueAt(fila, 3).toString());
            TxtNombreBar2.setText(TbActualizarTecnico.getValueAt(fila, 5).toString());
            TxtCorreo2.setText(TbActualizarTecnico.getValueAt(fila,6).toString());
            String[] fecha;
            fecha = TbActualizarTecnico.getValueAt(fila, 7).toString().split("-");
            TxtPassword2.setText(TbActualizarTecnico.getValueAt(fila, 8).toString());
            String ano = fecha[0];
            String mes = fecha[1];
            String dia = fecha[2];
            String fes = dia+"/"+mes+"/"+ano;
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            java.util.Date parse;
            //try {
                parse = formato.parse(fes);
                DateEmpleados2.setDate(parse);
            //} catch (ParseException ex) {
               
            
            
        } else {
            JOptionPane.showMessageDialog(null, "Selecione una fila" );
        }
    }

    private void limpiarCajaTecnico() {
         
        txtIdentificacion3.setText("");
        TxtNombres2.setText("");
        TxtPassword2.setText("");
        Txtapellidos2.setText("");
        TxtNombreBar2.setText("");
        TxtTelefono2.setText("");
        TxtCorreo2.setText("");
        
    
    }
}
